import debugger
import logging
import time

dbg = debugger.Debugger("atmega4809")
dbg.stop()
dbg.breakpointSWClearAll()
dbg.breakpointHWClear()
#logging.info(dbg.readRegs())
#logging.info(dbg.readSRAM(0x00, 1024))
#logging.info(dbg.readSREG())
#logging.info(dbg.readStackPointer())
event = dbg.pollEvent()
while event != None:
    event = dbg.pollEvent()
dbg.readRunningState()
print("Started running")
dbg.run()
dbg.readRunningState()
while True:
    if dbg.readRunningState() == False:
        event = dbg.pollEvent()
        while event != None:
            event = dbg.pollEvent()
        print("Started running")
        dbg.run()
    time.sleep(1)
#dbg.breakpointSWSet(0x154)
#dbg.pollEvent()
#dbg.pollEvent()
#time.sleep(1)
#dbg.pollEvent()
#dbg.pollEvent()
#dbg.run()
#dbg.pollEvent()
#print(dbg.readProgramCounter())
#print("\n")
#dbg.step()
#dbg.step()
#dbg.step()
#dbg.pollEvent()
#dbg.pollEvent()
#dbg.pollEvent()
#dbg.pollEvent()
#time.sleep(1)
#dbg.pollEvent()
#dbg.pollEvent()
#dbg.run()
#dbg.pollEvent()
#
#time.sleep(1)
#
#print(dbg.readProgramCounter())
#print(dbg.readProgramCounter())
#print("\n")
#dbg.run()
#dbg.pollEvent()
#dbg.pollEvent()
#dbg.pollEvent()
#dbg.pollEvent()
#logging.info(dbg.readRegs())

dbg.cleanup()